version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/Users/welentsai/Workspace/spring-projects/pring-boot-prometheus/docker-compose/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - '--config.file=/Users/welentsai/Workspace/spring-projects/pring-boot-prometheus/docker-compose/prometheus.yml'
      - '--enable-feature=exemplar-storage'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    depends_on:
      - prometheus

  networks:
    monitoring:
      driver: bridge