server:
  port: 8080

spring:
  application:
    name: my-spring-app

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      tags:
        application: ${spring.application.name}
      enabled: true
    prometheus:
      enabled: true